### ISSUE TITLE
GÓP Ý ĐỒ ÁN

### ISSUE THREAD

**Issue by longtt2705** [longtt2705/p4ds-Final#5]
Đồ án của nhóm mình đã được hoàn thành, mời các bạn đọc và góp ý để đồ án có hoàn thiện hơn. Chúng mình xin chân thành cảm ơn!

**Comment by trucnguyen13** [comment]
Một số nhận xét:

- Các bạn trình bày nội dung khá tốt và rõ ràng.
- Khai thác được nhiều câu hỏi hay, trọng tâm và thực tiễn.

Một chút góp ý:

- Nên thêm phần trực quan hóa vào hai câu hỏi 2 và câu hỏi 4 để người xem có cái nhìn chi tiết hơn. Như ở câu hỏi 2, các bạn nên show các năm gần đây. Đặc biết hơn là đánh giá chi tiết vào năm 2020, khi dịch bệnh hoành hành khiến đa số mọi người dành thời gian cách ly ở nhà, lúc đó ảnh hưởng đến xu hướng chơi game.

Trên đây là những nhận xét và góp ý của nhóm mình sau khi xem qua đồ án của các bạn. Chúc nhóm có 1 buổi vấn đáp thật tốt! 😎😎

**Comment by longtt2705** [comment]
Cảm ơn bạn vì những góp ý, nhóm mình sẽ tiếp nhận và bổ sung. Chúc nhóm bạn cũng sẽ có một buổi vấn đáp thật tốt!

**Comment by tien238lnd** [comment]
Chào các bạn, cho phép mình nhận xét nhé: mình thấy 4 câu hỏi các bạn đặt rất hay, nghe rất có tố chất phân tích kinh doanh. Các bạn chọn biểu đồ để vẽ cũng phù hợp, và nhận xét cũng rất đầy đủ, tinh tế. Phần tiền xử lý thì các bạn làm theo sườn của thầy nên cũng đầy đủ rồi, mình không có gì để nhận xét. Chúc các bạn vấn đáp tốt nhé. Cheers ^^
